#ifndef PCI_CLASSES_H
#define PCI_CLASSES_H

#include <stdint.h>

#define PCI_OLD_DEV 0x00
#define PCI_MASS_STORAGE_CONTROLLER 0x01
#define PCI_CLASS_MASS_STORAGE PCI_MASS_STORAGE_CONTROLLER
#define PCI_NETWORK_CONTROLLER 0x02
#define PCI_DISPLAY_CONTROLLER 0x03
#define PCI_MULTIMEDIA_DEVICE 0x04
#define PCI_MEMORY_CONTROLLER 0x05
#define PCI_BRIDGE_DEVICE 0x06
#define PCI_SIMPLE_COMS_CONTROLLER 0x07
#define PCI_BASE_SYS_PERIPHERALS 0x08
#define PCI_INPUT_DEVICES 0x09
#define PCI_DOCKING_STATIONS 0x0A
#define PCI_PROCESSORS 0x0B
#define PCI_SERIAL_BUS_CONTROLLER 0x0C
#define PCI_WIRELESS_CONTROLLER 0x0D
#define PCI_INTELLIGENT_IO_CONTROLLER 0x0E
#define PCI_SATELLITE_COM_CONTROLLER 0x0F
#define PCI_ENCRYPTION_DECRYPTION_CONTROLLER 0x10
#define PCI_DATA_ACQUISITION_AND_SIGNAL_PROCESSING_CONTROLLER 0x11

#define PCI_SUBCLASS_SATA 0x06
#define PCI_SUBCLASS_NVME 0x08

/**
 * Test whether a PCI base class is mass storage.
 * @date 2026-10-07
 */
int pci_is_mass_storage(uint8_t class_code);

#endif
